### ISSUE TITLE
Key error in extra_needed_columns for data

### ISSUE THREAD

**Issue by CristianAntochi** [JelleAalbers/flamedisx#29]
When trying to pass a data frame with data with the added columns of 'x_observed' and 'y_observed' there is a key error in the initialisation of the LogLikelihood. 
Somehow the extra columns added to the data are either removed or not considered in the likelihood before looking up the values in the correction maps.

**Comment by pelssers** [comment]
We looked into it and the issue is that the `x_observed` and `y_observed` columns are not simulated in `random_truth`. So even though data has the columns and they are kept when annotating, also random truth needs to be modified. So in the `SR1NRSource` you want to do something similar as was done in the SR0 Source:
https://github.com/JelleAalbers/flamedisx/blob/master/flamedisx/x1t_sr0.py#L82
